name: DSK config split
type: module
description: Provides suiting default config for config split.
package: DSK
core: 8.x
core_version_requirement: ^8 || ^9 || ^10
dependencies:
  - drupal:config_split
